# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sdx_controller.models.base_model_ import Model
from sdx_controller import util


class ConnectionQosUnit(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: int=None, strict: bool=None):  # noqa: E501
        """ConnectionQosUnit - a model defined in Swagger

        :param value: The value of this ConnectionQosUnit.  # noqa: E501
        :type value: int
        :param strict: The strict of this ConnectionQosUnit.  # noqa: E501
        :type strict: bool
        """
        self.swagger_types = {
            'value': int,
            'strict': bool
        }

        self.attribute_map = {
            'value': 'value',
            'strict': 'strict'
        }
        self._value = value
        self._strict = strict

    @classmethod
    def from_dict(cls, dikt) -> 'ConnectionQosUnit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The connection_qos_unit of this ConnectionQosUnit.  # noqa: E501
        :rtype: ConnectionQosUnit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> int:
        """Gets the value of this ConnectionQosUnit.


        :return: The value of this ConnectionQosUnit.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this ConnectionQosUnit.


        :param value: The value of this ConnectionQosUnit.
        :type value: int
        """

        self._value = value

    @property
    def strict(self) -> bool:
        """Gets the strict of this ConnectionQosUnit.


        :return: The strict of this ConnectionQosUnit.
        :rtype: bool
        """
        return self._strict

    @strict.setter
    def strict(self, strict: bool):
        """Sets the strict of this ConnectionQosUnit.


        :param strict: The strict of this ConnectionQosUnit.
        :type strict: bool
        """

        self._strict = strict
