# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from sdx_controller import util
from sdx_controller.models.base_model_ import Model


class L2vpnServiceIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """L2vpnServiceIdBody - a model defined in Swagger"""
        self.swagger_types = {}

        self.attribute_map = {}

    @classmethod
    def from_dict(cls, dikt) -> "L2vpnServiceIdBody":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The l2vpn_service_id_body of this L2vpnServiceIdBody.  # noqa: E501
        :rtype: L2vpnServiceIdBody
        """
        return util.deserialize_model(dikt, cls)
