version: '3.8'

services:

  # See https://hub.docker.com/_/mongo/ for documentation about
  # MongoDB Docker images.
  sdx-controller-mongodb-service:
    image: mongo:3.7
    container_name: sdx-controller-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: sdx
      MONGO_INITDB_ROOT_PASSWORD: passw
      MONGODB_DATA_DIR: /data/db
    volumes:
      # See https://docs.docker.com/storage/volumes/
      #
      # The 'Z' option tells Docker to label the content with a
      # private unshared label. Private volumes can only be used by
      # the current container.  See
      # https://docs.docker.com/engine/reference/commandline/run/
      - type: volume
        source: mongodb
        target: /data/db:Z

  sdx-controller-service:
    image: sdx-controller
    container_name: sdx-controller
    depends_on:
      - sdx-controller-mongodb-service
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      # Use sdx-controller-mongodb specified above.
      - MONGODB_CONNSTRING=mongodb://sdx:passw@sdx-controller-mongodb:27017/
      - SDX_HOST=aw-sdx-controller.renci.org
      - SDX_PORT=8080
      - SDX_VERSION=1.0.0
      - PUB_TOPIC=connection
      - SUB_QUEUE=sdx_q1
      - SUB_TOPIC=topo
      - SUB_QUEUE=topo
      - SUB_TOPIC=sdx_q1
      - MQ_HOST=aw-sdx-monitor.renci.org
      - DB_NAME=test-db
      - DB_CONFIG_TABLE_NAME=sdx-config-test-1
      - MANIFEST=README.md

  bapm-server-service:
    image: bapm-server
    container_name: bapm-server
    tty: true
    build: ./bapm_server
    environment:
      - ES_HOST=localhost
      - ES_PORT=9200
      - BAPM_MQ_HOST=amqp://guest:guest@aw-sdx-monitor.renci.org:5672/%2F
      - BAPM_EXCHANGE=measurement
      - BAPM_QUEUE=sdx_q_measurement
      - BAPM_ROUTING_KEY=measurement.bapm

volumes:
  mongodb:
