version: '3.8'

services:
  mq:
    #image: rabbitmq:3-management-alpine
    image: rabbitmq:latest
    container_name: simple-mq
    hostname: rabbitmq-container
    #volumes:
    #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #  - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #  - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - sdxnet

networks:
  sdxnet:
    external:
      name: sdxnet
