version: '3.8'

services:

  # See https://hub.docker.com/_/mongo/ for documentation about
  # MongoDB Docker images.
  mongodb-service:
    image: mongo:3.7
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DATA_DIR: ${MONGODB_DATA_DIR}
    volumes:
      # See https://docs.docker.com/storage/volumes/
      #
      # The 'Z' option tells Docker to label the content with a
      # private unshared label. Private volumes can only be used by
      # the current container.  See
      # https://docs.docker.com/engine/reference/commandline/run/
      - type: volume
        source: mongodb
        target: /data/db:Z

  sdx-controller-service:
    image: sdx-controller
    depends_on:
      - mongodb-service
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      # Use mongodb-service specified above.  Note that we do not use
      # the same MONGODB_CONNSTRING variable from .env here, because
      # that is helpful for running unit/integration tests.
      - MONGODB_CONNSTRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/
      - SDX_HOST=${SDX_HOST}
      - SDX_PORT=${SDX_PORT}
      - SDX_VERSION=${SDX_VERSION}
      - MQ_HOST=${MQ_HOST}
      - SUB_TOPIC=${SUB_TOPIC}
      - SUB_QUEUE=${SUB_QUEUE}
      - DB_NAME=${DB_NAME}
      - DB_CONFIG_TABLE_NAME=${DB_CONFIG_TABLE_NAME}

  # This is a single node elasticsearch with authentication and TLS
  # disabled, for testing/development.  See
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  # for a more elaborate setup.
  elasticsearch-service:
    image: elasticsearch:8.11.3
    ports:
      - ${ES_PORT}:${ES_PORT}
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    mem_limit: 1GB

  bapm-server-service:
    image: bapm-server
    depends_on:
      - elasticsearch
    tty: true
    build: ./bapm_server
    environment:
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - BAPM_MQ_HOST=${BAPM_MQ_HOST}
      - BAPM_EXCHANGE=${BAPM_EXCHANGE}
      - BAPM_QUEUE=${BAPM_QUEUE}
      - BAPM_ROUTING_KEY=${BAPM_ROUTING_KEY}

volumes:
  mongodb:
  elasticsearch-data:
