version: '3.8'

services:

  my-mongodb:
    image: mongo:3.7
    container_name: mongodb
    ports:
      - 27117:27017
    environment:
      # MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: sdx
      MONGO_INITDB_ROOT_PASSWORD: passw
      MONGODB_DATA_DIR: /data/db
    volumes:
      # named volumes
      - ~/mongodb:/data/db

  sdx-controller:
    image: sdx-controller
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      # update to sdx controller host name
      - MONGODB_CONNSTRING=mongodb://sdx:passw@152.54.3.143:27117/
      - SDX_HOST=aw-sdx-controller.renci.org
      - SDX_PORT=8080
      - SDX_VERSION=1.0.0
      - PUB_TOPIC=connection
      - SUB_QUEUE=sdx_q1
      - SUB_TOPIC=topo
      - SUB_QUEUE=topo
      - SUB_TOPIC=sdx_q1
      - MQ_HOST=aw-sdx-monitor.renci.org
      - DB_NAME=test-db
      - DB_CONFIG_TABLE_NAME=sdx-config-test-1
      - MANIFEST=README.md

  bapm-server:
    image: bapm-server
    # network_mode: "host"
    tty: true
    build: ./bapm_server
    environment:
      - ES_HOST=localhost
      - ES_PORT=9200
      - BAPM_MQ_HOST=amqp://guest:guest@aw-sdx-monitor.renci.org:5672/%2F
      - BAPM_EXCHANGE=measurement
      - BAPM_QUEUE=sdx_q_measurement
      - BAPM_ROUTING_KEY=measurement.bapm
