version: '3.8'

services:
  sdx-controller:
    image: sdx-controller
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      # update to sdx controller host name
      - SDX_HOST=aw-sdx-controller.renci.org
      - SDX_PORT=8080
      - SDX_VERSION=1.0.0
      - PUB_TOPIC=connection
      - SUB_QUEUE=sdx_q1
      - SUB_TOPIC=topo
      - SUB_QUEUE=topo
      - SUB_TOPIC=sdx_q1
      - MQ_HOST=aw-sdx-monitor.renci.org
      - DB_NAME=test-db
      - DB_CONFIG_TABLE_NAME=test-1
      - MANIFEST=README.md

  bapm-server:
    image: bapm-server
    network_mode: "host"
    tty: true
    build: ./bapm_server