version: '3.8'

services:
  sdx-controller:
    image: sdx-controller
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      - MQ_HOST=rabbitmq-container
      - MQ_PORT=5672
      - SDX_HOST=aw-sdx-controller.renci.org
      - SDX_PORT=8080
      - SDX_VERSION=1.0.0
      - MQ_NAME=hello
      - DB_NAME=test-db
      - MANIFEST=README.md
    networks:
      - sdxnet

networks:
  sdxnet:
    external:
      name: sdxnet
