version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    # image: rabbitmq:latest
    # container_name: simple-mq
    hostname: rabbitmq-container
    #volumes:
    #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #  - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #  - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - sdxnet

  sdx-controller:
    image: sdx-controller
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      # update to sdx controller host name
      - SDX_HOST=aw-sdx-controller.renci.org
      - SDX_PORT=8080
      - SDX_VERSION=1.0.0
      - PUB_TOPIC=connection
      - SUB_QUEUE=sdx_q1
      - SUB_TOPIC=topo
      - MQ_NAME=hello
      - MQ_HOST=aw-sdx-monitor.renci.org
      - DB_NAME=test-db
      - DB_CONFIG_TABLE_NAME=test-1
      - MANIFEST=README.md
    networks:
      - sdxnet

networks:
  sdxnet:
    external:
      name: sdxnet
