version: '3.8'

services:

  # See https://hub.docker.com/_/mongo/ for documentation about
  # MongoDB Docker images.
  sdx-controller-mongodb:
    image: mongo:3.7
    container_name: mongodb
    environment:
      # MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DATA_DIR: /data/db
    volumes:
      # Named volumes. The 'Z' option tells Docker to label the
      # content with a private unshared label. Private volumes can
      # only be used by the current container.  See
      # https://docs.docker.com/engine/reference/commandline/run/
      - ./db:/data/db:Z

  sdx-controller:
    image: sdx-controller
    container_name: sdx-controller
    tty: true
    build: ./
    ports:
      - 8080:8080
    environment:
      # Use sdx-controller-mongodb service specified above.
      - MONGODB_CONNSTRING=${MONGODB_CONNSTRING}
      - SDX_HOST=${SDX_HOST}
      - SDX_PORT=${SDX_PORT}
      - SDX_VERSION=${SDX_VERSION}
      - MQ_HOST=${MQ_HOST}
      - MQ_NAME=${MQ_NAME}
      - PUB_TOPIC=${PUB_TOPIC}
      - SUB_TOPIC=${SUB_TOPIC}
      - SUB_QUEUE=${SUB_QUEUE}
      - DB_NAME=${DB_NAME}
      - DB_CONFIG_TABLE_NAME=${DB_CONFIG_TABLE_NAME}

  bapm-server:
    image: bapm-server
    container_name: bapm-server
    # network_mode: "host"
    tty: true
    build: ./bapm_server
    environment:
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - BAPM_MQ_HOST=${BAPM_MQ_HOST}
      - BAPM_EXCHANGE=${BAPM_EXCHANGE}
      - BAPM_QUEUE=${BAPM_QUEUE}
      - BAPM_ROUTING_KEY=${BAPM_ROUTING_KEY}
