# A workflow to build and publish sdx-controllera container images.
# See https://docs.docker.com/build/ci/github-actions/.

name: Container images

on:
  push:
    branches:
      - "main"
  # TODO: building *and* publishing container images on pull requests
  # should be here only temporarily, while testing, because it
  # probably makes more sense to publish images built off only merged
  # code?
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Secrets used here are set under "repository secrets" at
      # https://github.com/atlanticwave-sdx/sdx-controller/settings/secrets/actions,
      # 
      # # See https://github.com/docker/login-action.
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Buildx is a Docker CLI plugin for extended build capabilities
      # with BuildKit.
      #
      # See https://github.com/docker/setup-buildx-action.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # See https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: awsdx/sdx-controller:latest
